# Generated by Django 5.1.7 on 2025-03-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LipApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='retail_price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
